### ISSUE TITLE
Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.

### ISSUE THREAD

**Issue by Jesniphat** [sengirab/ngAutocomplete#4]
**I use your package and I have problem like this when I try to go to another routing.**

**This is my simple code.**
@ViewChild(NgAutocompleteComponent) public completer: NgAutocompleteComponent;
  public listProductName = [
    {id:1, title:'aaaaaa'},
    {id:2, title:'bbbbbb'}
  ];
  public group = [
    CreateNewAutocompleteGroup(
      'Search / choose in / from list',
      'completer',this.listProductName,
      {titleKey: 'title', childrenKey: null}
    ),
  ];

**This is Error.**
ERROR Error: Uncaught (in promise): TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.
TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.
    at HTMLInputElement.proto.(anonymous function) [as removeEventListener] (http://localhost:4200/polyfills.bundle.js:4440:50)
    at NgDropdownDirective.ngOnDestroy (http://localhost:4200/vendor.bundle.js:47776:24)
    at callProviderLifecycles (http://localhost:4200/vendor.bundle.js:11417:18)
    at callElementProvidersLifecycles (http://localhost:4200/vendor.bundle.js:11386:13)
    at callLifecycleHooksChildrenFirst (http://localhost:4200/vendor.bundle.js:11370:17)
    at destroyView (http://localhost:4200/vendor.bundle.js:12711:5)
    at callViewAction (http://localhost:4200/vendor.bundle.js:12860:13)
    at execComponentViewsAction (http://localhost:4200/vendor.bundle.js:12772:13)
    at destroyView (http://localhost:4200/vendor.bundle.js:12710:5)
    at callViewAction (http://localhost:4200/vendor.bundle.js:12860:13)
    at HTMLInputElement.proto.(anonymous function) [as removeEventListener] (http://localhost:4200/polyfills.bundle.js:4440:50)
    at NgDropdownDirective.ngOnDestroy (http://localhost:4200/vendor.bundle.js:47776:24)
    at callProviderLifecycles (http://localhost:4200/vendor.bundle.js:11417:18)
    at callElementProvidersLifecycles (http://localhost:4200/vendor.bundle.js:11386:13)
    at callLifecycleHooksChildrenFirst (http://localhost:4200/vendor.bundle.js:11370:17)
    at destroyView (http://localhost:4200/vendor.bundle.js:12711:5)
    at callViewAction (http://localhost:4200/vendor.bundle.js:12860:13)
    at execComponentViewsAction (http://localhost:4200/vendor.bundle.js:12772:13)
    at destroyView (http://localhost:4200/vendor.bundle.js:12710:5)
    at callViewAction (http://localhost:4200/vendor.bundle.js:12860:13)
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:3490:31)
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:3461:17)
    at http://localhost:4200/polyfills.bundle.js:3539:17
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:3120:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:4090:33)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:3119:36)
    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:2887:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:3297:35)
    at ZoneTask.invokeTask [as invoke] (http://localhost:4200/polyfills.bundle.js:3198:21)
    at invokeTask (http://localhost:4200/polyfills.bundle.js:4122:14)

**Comment by realnsleo** [comment]
Facing the same issue here.

**Comment by snaik2064** [comment]
@sengirab facing the same issue while routing.

**Comment by vipswelt** [comment]
@sengirab please fix this issue...

**Comment by vipswelt** [comment]
Thanks for marking it as bug... i am really in need of this fix... can you please fix it ASAP ... @sengirab ?

**Comment by sengirab** [comment]
@vipswelt 
I will be investigating this evening. Hopefully also come with the fix.

**Comment by vipswelt** [comment]
isn't it done... ? @sengirab

**Comment by sengirab** [comment]
I've been kind off busy with work and at home @vipswelt.

Very sorry that i could't find the time to fix this issue last evening. Will be trying this evening again.

If you really need this issue to be fixed, you could fork and clone.

**Comment by vipswelt** [comment]
i am beginner in angular 2+, so i can't get much deeper into code now days, please fix it ASAP ...

**Comment by vipswelt** [comment]
![image](https://user-images.githubusercontent.com/28600288/33320569-b3c998f0-d468-11e7-94c5-403f10657a48.png)

**Comment by vipswelt** [comment]
i think its because we are not destroying ViewChild in component...

**Comment by vipswelt** [comment]
so it has to be fixed.. please do it once.. @sengirab

**Comment by vsainiwelt** [comment]
Hello @sengirab,

  I've fixed this issue, can i commit the code... ?

**Comment by sengirab** [comment]
@vsainiwelt Ofcourse, create a pull request and i'll review and accept.

**Comment by vsainiwelt** [comment]
Getting this error while pushing my changes...

![image](https://user-images.githubusercontent.com/34088137/33363526-b8e6910a-d506-11e7-9e20-cbe07bb12d33.png)

**Comment by sengirab** [comment]
@vsainiwelt I invited you to be a collaborator.

**Comment by vsainiwelt** [comment]
ok..

**Comment by vsainiwelt** [comment]
PR done.. please have a look over it....

**Comment by vsainiwelt** [comment]
what should i do to update my ngAutoComplete package.. ?

**Comment by vsainiwelt** [comment]
in my local project.. where i am getting eventlistener error

**Comment by sengirab** [comment]
@vsainiwelt Currently running NgAutoComplete package to test. Releasing a new version in just a minute.

All you have to do when it's released is just npm update ng-auto-complete

**Comment by vsainiwelt** [comment]
ohk.. thanks... @sengirab

**Comment by sengirab** [comment]
@vipswelt @vsainiwelt 
New version is on npm.

**Comment by vsainiwelt** [comment]
ok @sengirab ... these both ID's are mine... thanks... it working fine now... 👍

**Comment by Jesniphat** [comment]
Thank you so much.
